### ISSUE TITLE
Intercom.io - "can't have more than 120 active events" error

### ISSUE THREAD

**Issue by irmiller22** [segment-integrations/analytics.js-integration-intercom#16]
I have several other Segment integrations that are sending more than 120 active events (Mixpanel being one of them). I just turned on the Intercom.io integration yesterday, and I'm getting the following error message in the response on our production app:

`{"error_message":"Cannot have more than 120 active event names"}`

 ```
Request URL:https://api-iam.intercom.io/vjs/users/events
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:52.22.140.54:443
```

This is a lot of noise, and not something I'd like to see showing up on our live app. I'm stuck here, because I can't reduce the number of active events that we're tracking with other Segment integrations. Is there a way to turn off the noise, or at least selectively choose which events that are sent to Intercom.io?

**Comment by f2prateek** [comment]
You can use selective integrations in code or in the Segment UI if you're on a business plan https://segment.com/docs/sources/website/analytics.js/#selecting-integrations.

For future reference, please direct support questions to friends@segment.com
