### ISSUE TITLE
intercom: post-fix date traits with `_at`

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-intercom#2]
_From @ianstormtaylor on June 11, 2014 23:13_

Server-side we do this so that Intercom users can see nicely formatted dates, since Intercom doesn't recognize them automatically from the JSON sent. So we should change the client-side integration to do this as well. 

We'll need to make it backwards compatible with the old traits as well.

@calvinfo 

_Copied from original issue: segmentio/analytics.js-integrations#209_

**Comment by ndhoule** [comment]
Here's where we do it in the server-side integration: https://github.com/segmentio/integration-intercom/blob/61a47642a7e5fafeffdbd05597052c8ac51564a9/lib/index.js#L115

**Comment by hankim813** [comment]
this has been implemented https://github.com/segment-integrations/analytics.js-integration-intercom/blob/master/lib/index.js#L99-L104
