### ISSUE TITLE
migrate intercom inbox activator

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-intercom#3]
_From @reinpk on May 7, 2014 21:34_

from our side we have two different settings:

* **inbox** (boolean, whether to show the inbox)
* **activator** (string, custom css selector to use for the inbox)

Then Intercom added a UI checkbox to control whether the inbox shows. But! If an activator is passed, they’ll show it regardless of what their UI checkbox is set to.

So from the “right” way to do things, realistically their UI should just be the final decision on whether to show the inbox or not. But I guess they may have backwards compatibility issues with that, which is why they don’t do it?

From our side, we had been defaulting people to have the default activator of #IntercomDefaultWidget but that means that even if people turn off the inbox setting in Intercom, it will still be on cuz we’re sending an activator. So, if we want to fix it it will require a migration:

1. Set the new default for the activator to empty string.
2. Everyone with Intercom inbox off, and activator is #IntercomDefaultWidget replace the activator with empty string.
3. Remove the Intercom inbox setting.

What we want to end up with in the end is that we don’t control the default inbox being on at all, we just let people use a custom activator if they want (which will turn the inbox on).

cc @yields @ianstormtaylor 

_Copied from original issue: segmentio/analytics.js-integrations#138_

**Comment by ndhoule** [comment]
Seems like there's a related PR for this in https://github.com/segmentio/migrations/pull/1?

**Comment by hankim813** [comment]
> What we want to end up with in the end is that we don’t control the default inbox being on at all, we just let people use a custom activator if they want (which will turn the inbox on).

This has been implemented! :)
